name: Go Production Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -o app .

      - name: Run server (production mode)
        env:
          PORT: ${{ secrets.PORT }}
        run: |
          chmod +x ./app
          ./app &
          sleep 10
          curl http://localhost:${PORT}/ping || echo "Server did not respond"
