name: Production Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build steps bisa disesuaikan (contoh buat Go):
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build app
        run: go build -o app .

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PROD_SERVER_SSH_PORT }}
          script: |
            cd /path/to/your/app

            # Pull update dari repo via HTTPS pakai PAT token
            git remote set-url origin https://${{ secrets.PAT_2 }}@github.com/ricokurnia12/wonder-server.git
            git pull origin master

            # Restart app (sesuaikan, contoh pakai systemd)
            sudo systemctl restart your-app.service

            # Debug
            echo "Deploy selesai di server"
